# Generated by Django 6.0.3 on 2026-04-03 19:56

import medcare_connect.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile_last_known_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=medcare_connect.upload_paths.UploadToUnique('avatars')),
        ),
    ]
