# Generated by Django 6.0.8 on 2026-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile_insurance_use_in_estimates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance_coverage_by_category',
            field=models.JSONField(blank=True, default=dict, help_text="Taux par catégorie d'acte (niveau 2), ex. {'Hématologie': 70}."),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance_coverage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux global de prise en charge (0–100 %) pour les estimations panier/devis.', max_digits=5, null=True),
        ),
    ]
