# Generated by Django 6.0.4 on 2026-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceChecklistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.JSONField(blank=True, default=dict, help_text="Dict slug → bool (ex. {'hebergement_souverain': true, ...})")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist conformité CDP',
                'verbose_name_plural': 'Checklist conformité CDP',
            },
        ),
    ]
