# Generated by Django 6.0.3 on 2026-03-23 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoris',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoris',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='healthcare.organismedesante'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='photos',
            field=models.ManyToManyField(blank=True, to='healthcare.photo'),
        ),
        migrations.AddField(
            model_name='prestataireacte',
            name='acte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_actes', to='healthcare.actemedical'),
        ),
        migrations.AddField(
            model_name='prestataireacte',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_actes', to='healthcare.organismedesante'),
        ),
        migrations.AddField(
            model_name='priseenchargeacteassurance',
            name='acte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_overrides', to='healthcare.actemedical'),
        ),
        migrations.AddField(
            model_name='priseenchargeassurance',
            name='assurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='healthcare.assurance'),
        ),
        migrations.AddField(
            model_name='priseenchargeassurance',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='healthcare.organismedesante'),
        ),
        migrations.AddField(
            model_name='priseenchargeacteassurance',
            name='prise_en_charge_generale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acte_overrides', to='healthcare.priseenchargeassurance'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='healthcare.organismedesante'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organismes', to='healthcare.region'),
        ),
        migrations.AddField(
            model_name='review',
            name='organisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='healthcare.organismedesante'),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actemedical',
            name='service_medical_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='healthcare.servicemedical'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='type_organisme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organismes', to='healthcare.typeorganisme'),
        ),
        migrations.AlterUniqueTogether(
            name='favoris',
            unique_together={('patient', 'organisme')},
        ),
        migrations.AlterUniqueTogether(
            name='prestataireacte',
            unique_together={('organisme', 'acte')},
        ),
        migrations.AlterUniqueTogether(
            name='priseenchargeassurance',
            unique_together={('organisme', 'assurance')},
        ),
        migrations.AlterUniqueTogether(
            name='priseenchargeacteassurance',
            unique_together={('prise_en_charge_generale', 'acte')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('organisme', 'patient')},
        ),
        migrations.AlterUniqueTogether(
            name='actemedical',
            unique_together={('name', 'parent_service', 'service_medical_category')},
        ),
    ]
