# Generated by Django 6.0.3 on 2026-03-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismedesante',
            name='ninea',
            field=models.CharField(blank=True, help_text="Numéro d'identification nationale des entreprises et associations (NINEA), si applicable", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='raison_sociale',
            field=models.CharField(blank=True, help_text='Raison sociale légale si différente du nom commercial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organismedesante',
            name='name',
            field=models.CharField(help_text='Nom affiché sur la plateforme (nom commercial / enseigne)', max_length=255),
        ),
    ]
