# Generated by Django 6.0.3 on 2026-03-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_organismedesante_ninea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assurance',
            options={'ordering': ['segment', 'name']},
        ),
        migrations.AddField(
            model_name='assurance',
            name='segment',
            field=models.CharField(choices=[('privee_iard', 'Assurance privée (IARD / traditionnelle)'), ('digitale', 'Assurance santé digitale / plateforme'), ('regime_public', 'Régime public / institutionnel'), ('mutuelle', 'Mutuelle / mutualité solidaire'), ('programme', 'Programme ou initiative de couverture')], db_index=True, default='privee_iard', help_text='Segment réglementaire / commercial (hiérarchie document officiel)', max_length=32),
        ),
    ]
