# Generated by Django 6.0.3 on 2026-03-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_assurance_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotExamenPrefait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('teaser', models.CharField(blank=True, help_text='Courte phrase affichée sur la carte (ex. idéal avant intervention)', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Emoji ou clé d'icône", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Lot d'examens prédéfini",
                'verbose_name_plural': "Lots d'examens prédéfinis",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LotExamenPrefaitActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_memberships', to='healthcare.actemedical')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_actes', to='healthcare.lotexamenprefait')),
            ],
            options={
                'verbose_name': 'Acte du lot',
                'verbose_name_plural': 'Actes du lot',
                'ordering': ['order', 'pk'],
                'unique_together': {('lot', 'acte')},
            },
        ),
        migrations.AddField(
            model_name='lotexamenprefait',
            name='actes',
            field=models.ManyToManyField(related_name='lots_prefaits', through='healthcare.LotExamenPrefaitActe', to='healthcare.actemedical'),
        ),
    ]
