# Generated by Django 6.0.3 on 2026-03-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_lot_examen_prefait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priseenchargeassurance',
            name='global_coverage_rate',
        ),
        migrations.DeleteModel(
            name='PriseEnChargeActeAssurance',
        ),
    ]
