# Generated by Django 6.0.3 on 2026-04-03 19:56

import medcare_connect.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_remove_prise_en_charge_taux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=medcare_connect.upload_paths.UploadToUnique('insurance_logos')),
        ),
        migrations.AlterField(
            model_name='organismedesante',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=medcare_connect.upload_paths.UploadToUnique('logos')),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, upload_to=medcare_connect.upload_paths.UploadToUnique('organism_photos')),
        ),
        migrations.AlterField(
            model_name='servicemedical',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=medcare_connect.upload_paths.UploadToUnique('services')),
        ),
    ]
