# Generated by Cursor on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    La base (SQLite prod) contient déjà ces colonnes NOT NULL / NULL sur
    healthcare_organismedesante, mais elles n'étaient pas déclarées dans le modèle.

    On aligne l'état Django (ORM) sans toucher au schéma DB : sinon Django tenterait
    d'ajouter des colonnes qui existent déjà.
    """

    dependencies = [
        ("healthcare", "0007_image_upload_unique_maxlen"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="organismedesante",
                    name="sans_rendez_vous",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="organismedesante",
                    name="accepte_tiers_payant",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="organismedesante",
                    name="prises_sang_domicile",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="organismedesante",
                    name="access_pmr",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="organismedesante",
                    name="horaires_complement",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]

