# Generated by Django 6.0.4 on 2026-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_organismedesante_missing_prod_fields_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataireacte',
            name='delai',
            field=models.CharField(blank=True, choices=[('', 'Non précisé'), ('immediat', 'Immédiat (urgence)'), ('30min', 'Moins de 30 min'), ('1h', "Moins d'1 heure"), ('2h', 'Moins de 2 heures'), ('4h', 'Dans la journée (≤ 4h)'), ('24h', 'Sous 24 h'), ('48h', 'Sous 48 h'), ('72h', 'Sous 72 h'), ('7j', 'Sous 7 jours'), ('rdv', 'Sur rendez-vous')], db_index=True, default='', help_text="Délai indicatif d'obtention du résultat ou de réalisation.", max_length=16),
        ),
    ]
