# Generated by Django 6.0.4 on 2026-05-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_subscriptions(apps, schema_editor):
    SubscriptionFeature = apps.get_model("healthcare", "SubscriptionFeature")
    SubscriptionPlan = apps.get_model("healthcare", "SubscriptionPlan")
    SubscriptionPlanFeature = apps.get_model("healthcare", "SubscriptionPlanFeature")
    OrganismeDeSante = apps.get_model("healthcare", "OrganismeDeSante")

    specs = [
        ("listing", "Listing annuaire", "Visible dans les résultats de recherche", 10),
        ("profil_public", "Fiche publique complète", "Page profil détaillée", 20),
        ("assurances", "Assurances déclarées", "Assurances acceptées affichées", 30),
        ("whatsapp_devis", "Devis WhatsApp", "Canal devis automatique", 40),
        ("dashboard_basic", "Tableau de bord", "Statistiques de base", 50),
        ("dashboard_advanced", "Tableau de bord avancé", "Graphiques et exports", 60),
        ("reservations", "Réservations en ligne", "Prise de RDV via MedCare", 70),
        ("medplaque", "MedPlaque NFC", "Plaque / QR accueil", 80),
        ("stats_mensuelles", "Statistiques mensuelles", "Rapports périodiques", 90),
        ("api_partenaires", "API partenaires", "Intégrations techniques", 100),
        ("multi_sites", "Multi-sites", "Plusieurs établissements", 110),
        ("support_prioritaire", "Support prioritaire", "Assistance renforcée", 120),
        ("badge_pionnier", "Badge Partenaire Pionnier", "Visibilité programme Pionnier", 5),
    ]
    feat_by_code = {}
    for code, label, desc, order in specs:
        f, _ = SubscriptionFeature.objects.get_or_create(
            code=code,
            defaults={"label": label, "description": desc, "order": order},
        )
        feat_by_code[code] = f

    def ensure_plan(slug, defaults):
        plan, _ = SubscriptionPlan.objects.get_or_create(slug=slug, defaults=defaults)
        return plan

    pionnier = ensure_plan(
        "pionnier",
        {
            "name": "Pionnier",
            "slug": "pionnier",
            "short_description": "Offre gratuite — programme Partenaires Pionniers (M0–M6, indicatif).",
            "monthly_price_fcfa": 0,
            "is_default": True,
            "is_public": True,
            "is_pioneer_offer": True,
            "order": 0,
            "trial_months": 6,
        },
    )
    essentiel = ensure_plan(
        "essentiel",
        {
            "name": "Essentiel",
            "slug": "essentiel",
            "short_description": "Petites structures — réservations et stats mensuelles.",
            "monthly_price_fcfa": 25000,
            "is_default": False,
            "is_public": True,
            "order": 10,
        },
    )
    pro = ensure_plan(
        "pro",
        {
            "name": "Pro",
            "slug": "pro",
            "short_description": "Dashboard complet, MedPlaque, API sur demande.",
            "monthly_price_fcfa": 50000,
            "is_default": False,
            "is_public": True,
            "order": 20,
        },
    )
    ensure_plan(
        "reseau",
        {
            "name": "Réseau",
            "slug": "reseau",
            "short_description": "Réseaux d'établissements — facturation négociée hors plateforme.",
            "monthly_price_fcfa": 100000,
            "is_default": False,
            "is_public": True,
            "order": 30,
        },
    )

    def link(plan, codes):
        for c in codes:
            SubscriptionPlanFeature.objects.get_or_create(
                plan=plan,
                feature=feat_by_code[c],
                defaults={"included": True},
            )

    link(
        pionnier,
        [
            "listing",
            "profil_public",
            "assurances",
            "whatsapp_devis",
            "dashboard_basic",
            "badge_pionnier",
        ],
    )
    link(
        essentiel,
        [
            "listing",
            "profil_public",
            "assurances",
            "whatsapp_devis",
            "dashboard_basic",
            "dashboard_advanced",
            "reservations",
            "stats_mensuelles",
        ],
    )
    pro_codes = [
        "listing",
        "profil_public",
        "assurances",
        "whatsapp_devis",
        "dashboard_basic",
        "dashboard_advanced",
        "reservations",
        "medplaque",
        "stats_mensuelles",
        "api_partenaires",
        "multi_sites",
        "support_prioritaire",
    ]
    link(SubscriptionPlan.objects.get(slug="pro"), pro_codes)
    link(SubscriptionPlan.objects.get(slug="reseau"), pro_codes)

    default = SubscriptionPlan.objects.filter(is_default=True).first() or pionnier
    OrganismeDeSante.objects.filter(subscription_plan__isnull=True).update(
        subscription_plan_id=default.pk
    )


def seed_subscriptions_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_prestataireacte_delai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique stable (ex. whatsapp_devis, medplaque).', max_length=64, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Fonctionnalité d'abonnement",
                'verbose_name_plural': "Fonctionnalités d'abonnement",
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.TextField(blank=True)),
                ('monthly_price_fcfa', models.PositiveIntegerField(default=0, help_text='Montant mensuel indicatif en FCFA (0 = gratuit). Pas de prélèvement automatique.')),
                ('is_default', models.BooleanField(default=False, help_text='Attribuée aux nouvelles structures si aucune autre logique.')),
                ('is_public', models.BooleanField(default=True, help_text='Visible sur la page « Abonnement » côté structure.')),
                ('is_pioneer_offer', models.BooleanField(default=False, help_text="Affiche un badge type « Partenaire Pionnier » dans l'UI.")),
                ('trial_months', models.PositiveSmallIntegerField(blank=True, help_text="Durée d'essai en mois (affichage seulement).", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Formule d'abonnement",
                'verbose_name_plural': "Formules d'abonnement",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée par la structure')], db_index=True, default='pending', max_length=20)),
                ('message_from_structure', models.TextField(blank=True, verbose_name='Message de la structure')),
                ('staff_note', models.TextField(blank=True, verbose_name='Note interne (équipe MedCare)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_change_requests', to='healthcare.organismedesante')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('previous_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='healthcare.subscriptionplan', verbose_name='Formule au moment de la demande')),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='healthcare.subscriptionplan', verbose_name='Formule demandée')),
            ],
            options={
                'verbose_name': 'Demande de changement de formule',
                'verbose_name_plural': 'Demandes de changement de formule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organismes', to='healthcare.subscriptionplan', verbose_name="Formule d'abonnement"),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True, help_text='Si faux, la ligne sert à documenter une exclusion explicite (rare).')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='healthcare.subscriptionfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='healthcare.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Fonctionnalité incluse dans la formule',
                'verbose_name_plural': 'Fonctionnalités incluses par formule',
                'ordering': ['feature__order', 'feature__label'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.RunPython(seed_subscriptions, seed_subscriptions_reverse),
        migrations.AlterField(
            model_name='organismedesante',
            name='subscription_plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='organismes',
                to='healthcare.subscriptionplan',
                verbose_name="Formule d'abonnement",
            ),
        ),
    ]
