# Generated by Django 6.0.4 on 2026-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismedesante',
            name='subscription_auto_renew',
            field=models.BooleanField(default=True, verbose_name='Renouvellement automatique'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='subscription_renewal_at',
            field=models.DateField(blank=True, help_text="Prochaine échéance (renouvellement). Une alerte J-30 est affichée à l'admin.", null=True, verbose_name="Échéance d'abonnement"),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='subscription_started_at',
            field=models.DateField(blank=True, help_text="Date d'entrée sur la formule actuelle (informatif, sert au calcul d'échéance).", null=True, verbose_name='Début abonnement'),
        ),
    ]
