# Generated by Django 6.0.4 on 2026-05-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_organismedesante_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrelevementZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nom court de la zone (ex : « Mermoz », « Plateau », « Banlieue »).', max_length=120)),
                ('forfait_fcfa', models.PositiveIntegerField(default=0, help_text='Tarif du déplacement en FCFA (0 = gratuit).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelevement_zones', to='healthcare.organismedesante')),
            ],
            options={
                'verbose_name': 'Zone de prélèvement à domicile',
                'verbose_name_plural': 'Zones de prélèvement à domicile',
                'ordering': ['order', 'label'],
                'unique_together': {('organisme', 'label')},
            },
        ),
    ]
