# Generated by Django 6.0.3 on 2026-05-15 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_prelevementzone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('tarifs_delais_comment', models.TextField(blank=True, help_text='Retour libre sur tarifs et délais (unique champ texte, comme la démo structures).', verbose_name='Tarifs & délais')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actes', models.ManyToManyField(blank=True, help_text='Actes médicaux concernés (niveau 3 / segmentation catalogue).', related_name='platform_reviews', to='healthcare.actemedical')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis plateforme',
                'verbose_name_plural': 'Avis plateforme',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('patient',), name='unique_platform_review_per_patient')],
            },
        ),
    ]
