# Generated by Django 6.0.3 on 2026-05-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_platform_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
