# Generated by Django 6.0.3 on 2026-05-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_remove_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismedesante',
            name='assurances_tarifs_delais',
            field=models.TextField(blank=True, help_text='Saisie libre : tiers payant, délais de prise en charge, documents requis, etc.', verbose_name='Tarifs & délais (assurances)'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='catalogue_tarifs_delais',
            field=models.TextField(blank=True, help_text='Saisie libre côté structure : transparence tarifaire, délais d’exécution, particularités. Complète les cases « actes proposés » du parcours simplifié.', verbose_name='Tarifs & délais (catalogue actes)'),
        ),
    ]
