# Generated by Django 5.2.16 on 2026-07-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0023_organisme_dashboard_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prelevementzone',
            options={'ordering': ['order', 'label'], 'verbose_name': 'Zone de prestation à domicile', 'verbose_name_plural': 'Zones de prestation à domicile'},
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='profession',
            field=models.CharField(blank=True, choices=[('', '— Sélectionnez votre profession —'), ('kinesitherapeute', 'Kinésithérapeute'), ('infirmier', 'Infirmier(ère)'), ('sage_femme', 'Sage-femme'), ('orthophoniste', 'Orthophoniste'), ('psychomotricien', 'Psychomotricien(ne)'), ('psychologue', 'Psychologue'), ('dieteticien', 'Diététicien(ne)-nutritionniste'), ('orthoptiste', 'Orthoptiste'), ('ergotherapeute', 'Ergothérapeute'), ('pedicure_podologue', 'Pédicure-podologue')], default='', help_text='Uniquement pour les praticiens indépendants paramédicaux.', max_length=50, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='prestataireacte',
            name='rdv_prerequisites',
            field=models.TextField(blank=True, help_text='Message personnalisé pour vos patients (rappels automatiques).', verbose_name='Consignes / prérequis RDV (structure)'),
        ),
        migrations.AlterField(
            model_name='prestataireacte',
            name='rdv_prerequisites_active',
            field=models.BooleanField(default=True, verbose_name='Diffuser les consignes au patient'),
        ),
    ]
