# Generated by Django 6.0.8 on 2026-10-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0024_add_profession_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismedesante',
            name='account_nature',
            field=models.CharField(choices=[('structure', 'Structure de soins'), ('praticien', 'Praticien indépendant')], db_index=True, default='structure', max_length=20, verbose_name='Nature du compte'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='exercise_modes',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['cabinet', 'domicile']", verbose_name="Modes d'exercice"),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='intervention_zone',
            field=models.CharField(blank=True, help_text='Ex: Dakar, Almadies, Ouest-Foire...', max_length=255, null=True, verbose_name="Zone d'intervention (domicile)"),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='is_individual',
            field=models.BooleanField(db_index=True, default=False, help_text="Si vrai, l'individu assume son nom propre, sans fiche directe dans l'annuaire (Art. 10, 17, 19).", verbose_name='Praticien indépendant individuel'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='ordre_numero',
            field=models.CharField(blank=True, help_text='Numéro ONMS pour médecin, ou titre / ADELI selon la profession.', max_length=100, null=True, verbose_name="Numéro d'inscription à l'Ordre ou titre professionnel"),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='piliers_actifs',
            field=models.ManyToManyField(blank=True, help_text='Piliers choisis par la structure, indépendamment de son type/topologie.', related_name='organismes_actifs', to='healthcare.servicemedical', verbose_name="Piliers d'activité choisis librement"),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Liste des spécialités déclarées (ex: 43 spécialités médicales / 7 familles, etc.).', verbose_name='Spécialités professionnelles'),
        ),
        migrations.AddField(
            model_name='organismedesante',
            name='topology_type',
            field=models.CharField(blank=True, choices=[('simple', 'Structure simple (un seul site)'), ('multiservice', 'Établissement multi-services (un lieu, plusieurs services)'), ('multisite', 'Réseau multi-sites (un métier, plusieurs lieux)')], default='simple', help_text="Uniquement la topologie (nombre de nœuds), découplée des piliers d'activité.", max_length=30, verbose_name="Topologie d'établissement"),
        ),
        migrations.AlterField(
            model_name='organismedesante',
            name='profession',
            field=models.CharField(blank=True, choices=[('', '— Sélectionnez votre profession —'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier(ère)'), ('kinesitherapeute', 'Kinésithérapeute'), ('sage_femme', 'Sage-femme'), ('psychologue', 'Psychologue'), ('autre', 'Autre paramédical'), ('orthophoniste', 'Orthophoniste'), ('psychomotricien', 'Psychomotricien(ne)'), ('dieteticien', 'Diététicien(ne)-nutritionniste'), ('orthoptiste', 'Orthoptiste'), ('ergotherapeute', 'Ergothérapeute'), ('pedicure_podologue', 'Pédicure-podologue')], default='', help_text='Profession du praticien indépendant.', max_length=50, verbose_name='Profession'),
        ),
        migrations.CreateModel(
            name='PrestationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(db_index=True, help_text='Clé publique unique du ticket (ex: cheikh-kine-1a2b).', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Ex: Kiné respiratoire adulte, à domicile', max_length=255, verbose_name='Titre de la prestation')),
                ('description', models.TextField(blank=True, verbose_name='Description de la prestation')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif (FCFA)')),
                ('mode', models.CharField(choices=[('domicile', 'À domicile'), ('cabinet', 'Au cabinet')], default='domicile', max_length=50, verbose_name='Modalité')),
                ('zone', models.CharField(blank=True, default='Dakar', max_length=255, verbose_name="Zone d'intervention")),
                ('disponibilite', models.CharField(default='Créneaux sur demande', max_length=120, verbose_name='Disponibilité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ticket actif')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de consultations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='healthcare.actemedical', verbose_name='Acte médical rattaché')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='healthcare.organismedesante', verbose_name='Praticien')),
            ],
            options={
                'verbose_name': 'Ticket de prestation',
                'verbose_name_plural': 'Tickets de prestation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté')], db_index=True, default='approved', max_length=20, verbose_name='Statut')),
                ('role_title', models.CharField(blank=True, help_text='Ex: Kinésithérapeute vacataire, Médecin consultant', max_length=120, verbose_name='Rôle / Spécialité exercée')),
                ('days_schedule', models.JSONField(blank=True, default=list, help_text="Ex: ['Lundi matin (8h-12h)', 'Jeudi après-midi (14h-18h)']", verbose_name='Jours et plages de présence')),
                ('notes', models.TextField(blank=True, verbose_name="Notes ou conditions d'affiliation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations_praticien', to='healthcare.organismedesante', verbose_name='Praticien indépendant')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations_structure', to='healthcare.organismedesante', verbose_name="Structure d'accueil")),
            ],
            options={
                'verbose_name': 'Affiliation Praticien ↔ Structure',
                'verbose_name_plural': 'Affiliations Praticien ↔ Structure',
                'ordering': ['-created_at'],
                'unique_together': {('praticien', 'structure')},
            },
        ),
    ]
