# Generated by Django 6.0.8 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0025_organismedesante_account_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioneraffiliation',
            name='initiated_by',
            field=models.CharField(choices=[('praticien', 'Praticien'), ('structure', 'Structure')], default='praticien', help_text='Qui a initié le rattachement : le praticien (demande) ou la structure (invitation)', max_length=20, verbose_name='Initié par'),
        ),
        migrations.AlterField(
            model_name='practitioneraffiliation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('invited', 'Invitation envoyée'), ('approved', 'Validé'), ('rejected', 'Rejeté')], db_index=True, default='approved', max_length=20, verbose_name='Statut'),
        ),
    ]
