# Generated by Django 6.0.8 on 2026-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0026_affiliation_initiated_by_invited_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismedesante',
            name='type_libre',
            field=models.CharField(blank=True, default='', help_text='Label libre choisi par la structure (ex: Clinique, Laboratoire…). Indicatif — ne connecte pas automatiquement les piliers.', max_length=120, verbose_name='Type de structure (listing indicatif)'),
        ),
    ]
