# Generated by Django 6.0.3 on 2026-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('internal', 'Message Interne'), ('whatsapp_request', 'Demande WhatsApp'), ('system', 'Message Système')], default='internal', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('whatsapp_data', models.JSONField(blank=True, help_text='Données du message WhatsApp (numéro, texte pré-rempli, items panier)', null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Nouveau Message'), ('whatsapp', 'Demande WhatsApp'), ('review', 'Nouvel Avis'), ('cart', 'Modification Panier'), ('devis', 'Devis Généré'), ('profile_view', 'Consultation de Profil'), ('system', 'Notification Système'), ('approval', 'Approbation de Compte')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, help_text='URL interne vers la ressource concernée', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
