# Generated by Django 6.0.4 on 2026-05-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Nouveau Message'), ('whatsapp', 'Demande WhatsApp'), ('review', 'Nouvel Avis'), ('cart', 'Modification Panier'), ('devis', 'Devis Généré'), ('rdv', 'Rendez-vous'), ('assurance', 'Assurance'), ('prelevement', 'Prélèvement à domicile'), ('profile_view', 'Consultation de Profil'), ('system', 'Notification Système'), ('approval', 'Approbation de Compte')], max_length=20),
        ),
    ]
