# Generated by Django 6.0.4 on 2026-05-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rendezvous_source_rendezvous_walk_in_motif_and_more'),
        ('cart', '0005_devispart'),
        ('messaging', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='devis_part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='cart.devispart'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('general', 'Général'), ('devis', 'Devis'), ('rdv', 'Rendez-vous')], default='general', max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='appointments.rendezvous'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='thread_status',
            field=models.CharField(choices=[('active', 'Actif'), ('waiting', 'En attente'), ('closed', 'Clos')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='messaging.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('internal', 'Message Interne'), ('whatsapp_request', 'Demande WhatsApp'), ('system', 'Message Système'), ('status_card', 'Carte statut'), ('choice', 'Choix guidé')], default='internal', max_length=20),
        ),
    ]
