# Generated by Django 6.0.4 on 2026-05-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0005_devispart'),
        ('healthcare', '0016_service_medical_pillar_icons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('start', models.DateTimeField(verbose_name='Début du créneau')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin du créneau')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('confirmed', 'Confirmé'), ('declined', 'Refusé'), ('cancelled', 'Annulé'), ('completed', 'Honoré'), ('no_show', 'Absent')], default='requested', max_length=20)),
                ('actes_snapshot', models.JSONField(blank=True, default=list)),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_patient', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=500, help_text='Frais de réservation — affichage uniquement, encaissement prévu à M6.', max_digits=8)),
                ('patient_note', models.TextField(blank=True)),
                ('prestataire_note', models.TextField(blank=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('cancelled_by', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='cart.devis')),
                ('devis_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='cart.devispart')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='healthcare.organismedesante')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['organisme', 'status', 'start'], name='appointment_organis_296db6_idx'), models.Index(fields=['patient', 'status', 'start'], name='appointment_patient_9d1ffc_idx')],
            },
        ),
    ]
