# Generated by Django 6.0.4 on 2026-05-30 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rendezvous_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='source',
            field=models.CharField(choices=[('online', 'En ligne'), ('walk_in', 'Sur place')], default='online', max_length=12),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='walk_in_motif',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motif (sur place)'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='walk_in_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom (sur place)'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='walk_in_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone (sur place)'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient de la plateforme. Vide pour un RDV saisi sur place.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL),
        ),
    ]
