# Generated by Django 6.0.8 on 2026-10-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rdvreminderschedule_organisme'),
        ('healthcare', '0025_organismedesante_account_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdvreminderschedule',
            name='organisme',
            field=models.ForeignKey(blank=True, help_text='Vide = règle plateforme. Renseigné = règle propre à la structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdv_reminder_schedules', to='healthcare.organismedesante'),
        ),
    ]
