"""
Taux indicatifs de prise en charge par assurance et catégorie d'acte (niveau 2).

Source : maquettes patient (COVERAGE_RATES) — estimations, pas contrat réel.
Les clés d'assurance sont des libellés courts ; voir `assurance_rates_lookup_key`.
"""

# {libellé assurance: {catégorie niveau 2: taux %} }
COVERAGE_RATES_BY_ASSURANCE = {
    "CMU": {
        "Hématologie": 70,
        "Biochimie & Ionogramme": 70,
        "Sérologie & Virologie": 60,
        "Bactériologie": 70,
        "Radiographie": 70,
        "Échographie": 60,
        "Scanner (TDM)": 50,
        "Soins infirmiers": 80,
        "Médecine générale": 80,
    },
    "CNAM": {
        "Hématologie": 80,
        "Hémostase / Coagulation": 80,
        "Biochimie & Ionogramme": 80,
        "Sérologie & Virologie": 70,
        "Bactériologie": 80,
        "Endocrinologie": 70,
        "Marqueurs tumoraux": 70,
        "Radiographie": 80,
        "Échographie": 80,
        "Scanner (TDM)": 70,
        "IRM": 60,
        "Cardiologie": 80,
        "Soins infirmiers": 90,
    },
    "IPM": {
        "Hématologie": 80,
        "Hémostase / Coagulation": 80,
        "Biochimie & Ionogramme": 80,
        "Sérologie & Virologie": 80,
        "Bactériologie": 80,
        "Endocrinologie": 80,
        "Marqueurs tumoraux": 80,
        "Fertilité / AMP": 60,
        "Radiographie": 80,
        "Échographie": 80,
        "Échodoppler": 80,
        "Scanner (TDM)": 80,
        "IRM": 70,
        "Cardiologie": 80,
        "Pneumologie": 80,
        "Soins infirmiers": 90,
        "Rhumatologie / Orthopédie": 70,
        "Kinésithérapie": 70,
    },
    "IPRES": {
        "Hématologie": 75,
        "Biochimie & Ionogramme": 75,
        "Sérologie & Virologie": 70,
        "Bactériologie": 75,
        "Radiographie": 75,
        "Échographie": 70,
        "Scanner (TDM)": 60,
        "Soins infirmiers": 80,
    },
    "FNR": {
        "Hématologie": 80,
        "Biochimie & Ionogramme": 80,
        "Sérologie & Virologie": 75,
        "Radiographie": 80,
        "Échographie": 75,
        "Scanner (TDM)": 65,
        "Soins infirmiers": 85,
    },
    "MSAE": {
        "Hématologie": 85,
        "Biochimie & Ionogramme": 85,
        "Sérologie & Virologie": 80,
        "Bactériologie": 85,
        "Radiographie": 85,
        "Échographie": 80,
        "Scanner (TDM)": 70,
        "IRM": 60,
        "Soins infirmiers": 90,
    },
    "AXA Assurances Sénégal": {
        "Hématologie": 90,
        "Hémostase / Coagulation": 90,
        "Biochimie & Ionogramme": 90,
        "Immunologie & Auto-immunité": 85,
        "Sérologie & Virologie": 90,
        "Bactériologie": 90,
        "Endocrinologie": 90,
        "Marqueurs tumoraux": 85,
        "Fertilité / AMP": 70,
        "Radiographie": 90,
        "Échographie": 90,
        "Échodoppler": 90,
        "Scanner (TDM)": 90,
        "IRM": 85,
        "Biopsies guidées": 80,
        "Cardiologie": 90,
        "Pneumologie": 90,
        "Gastro-entérologie": 85,
        "Neurologie": 85,
        "ORL": 85,
        "Ophtalmologie": 85,
        "Soins infirmiers": 90,
        "Rhumatologie / Orthopédie": 85,
        "Kinésithérapie": 80,
        "Dialyse / Néphrologie": 85,
        "Psychologie": 70,
        "Psychiatrie": 70,
        "Consultations dentaires": 80,
        "Soins conservateurs": 80,
        "Endodontie": 75,
        "Chirurgie dentaire": 80,
    },
    "Allianz / SanlamAllianz": {
        "Hématologie": 85,
        "Biochimie & Ionogramme": 85,
        "Sérologie & Virologie": 85,
        "Bactériologie": 85,
        "Endocrinologie": 85,
        "Marqueurs tumoraux": 80,
        "Radiographie": 85,
        "Échographie": 85,
        "Échodoppler": 85,
        "Scanner (TDM)": 80,
        "IRM": 75,
        "Cardiologie": 85,
        "Soins infirmiers": 90,
        "Rhumatologie / Orthopédie": 80,
        "Kinésithérapie": 75,
        "Consultations dentaires": 75,
        "Soins conservateurs": 75,
    },
    "Tanel Health (Afiyah)": {
        "Hématologie": 80,
        "Biochimie & Ionogramme": 80,
        "Sérologie & Virologie": 75,
        "Bactériologie": 80,
        "Radiographie": 75,
        "Échographie": 75,
        "Scanner (TDM)": 65,
        "Soins infirmiers": 85,
    },
    "Susu Africa": {
        "Hématologie": 70,
        "Biochimie & Ionogramme": 70,
        "Sérologie & Virologie": 65,
        "Radiographie": 65,
        "Échographie": 65,
    },
    "Sammanté": {
        "Hématologie": 60,
        "Biochimie & Ionogramme": 60,
        "Sérologie & Virologie": 55,
        "Radiographie": 55,
        "Échographie": 55,
        "Soins infirmiers": 70,
    },
    "Plan Sésame": {
        "Hématologie": 100,
        "Biochimie & Ionogramme": 100,
        "Sérologie & Virologie": 100,
        "Bactériologie": 100,
        "Radiographie": 100,
        "Échographie": 100,
        "Scanner (TDM)": 100,
        "Soins infirmiers": 100,
        "Médecine générale": 100,
    },
    "Mutuelles communautaires CMU": {
        "Hématologie": 60,
        "Biochimie & Ionogramme": 60,
        "Sérologie & Virologie": 55,
        "Bactériologie": 60,
        "Radiographie": 55,
        "Soins infirmiers": 70,
    },
}

# Sous-chaînes du nom Assurance (minuscules) → clé COVERAGE_RATES_BY_ASSURANCE
_ASSURANCE_NAME_HINTS = (
    ("cmu", "CMU"),
    ("mutuelles de santé communautaires", "Mutuelles communautaires CMU"),
    ("mutuelles communautaires", "Mutuelles communautaires CMU"),
    ("cnam", "CNAM"),
    ("icamo", "CNAM"),
    ("css", "CNAM"),
    ("ipm", "IPM"),
    ("ipres", "IPRES"),
    ("fnr", "FNR"),
    ("msae", "MSAE"),
    ("plan sésame", "Plan Sésame"),
    ("axa", "AXA Assurances Sénégal"),
    ("allianz", "Allianz / SanlamAllianz"),
    ("sanlam", "Allianz / SanlamAllianz"),
    ("tanel", "Tanel Health (Afiyah)"),
    ("afiyah", "Tanel Health (Afiyah)"),
    ("susu", "Susu Africa"),
    ("sammant", "Sammanté"),
)
