# Generated by Django 6.0.3 on 2026-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Nom optionnel pour identifier le panier (ex: 'Bilan complet')", max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('saved', 'Sauvegardé'), ('converted', 'Converti en devis'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, help_text='Notes/demandes spécifiques du patient', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article du Panier',
                'verbose_name_plural': 'Articles du Panier',
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('total_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_patient', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('viewed', 'Consulté'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('details', models.JSONField(help_text='Snapshot détaillé des items, prix et taux au moment de la génération')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
