# Generated by Django 6.0.3 on 2026-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chariot', 'verbose_name_plural': 'Chariots'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article du chariot', 'verbose_name_plural': 'Articles du chariot'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, help_text="Nom optionnel pour identifier le chariot (ex: 'Bilan complet')", max_length=255, null=True),
        ),
    ]
