# Generated by Django 6.0.4 on 2026-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_verbose_chariot'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='last_relanced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='relance_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nombre de relances WhatsApp envoyées (max 2 avant archivage automatique).'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('viewed', 'Consulté'), ('relanced', 'Relancé'), ('expired', 'Expiré'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
    ]
