# Generated by Django 6.0.8 on 2026-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_insurance_user_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article du panier', 'verbose_name_plural': 'Articles du panier'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='insurance_user_override',
            field=models.BooleanField(default=False, help_text="Le patient a choisi manuellement l'assurance (ou « sans assurance ») sur le panier."),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, help_text="Nom optionnel pour identifier le panier (ex: 'Bilan complet')", max_length=255, null=True),
        ),
    ]
