# Generated by Django 6.0.4 on 2026-05-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_devis_created_template_sous_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='patient_wa_me_message_acte',
            field=models.TextField(default="Bonjour, je vous contacte via MedCare Connect. Je souhaite réserver un rendez-vous pour l'examen « {{ acte.name }} » (établissement « {{ org.name }} »).", help_text='Lien WhatsApp à côté de chaque acte. Ex. {{ acte.name }} pour l’examen, {{ org.name }} pour l’établissement.', verbose_name='Message WhatsApp (par examen)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='patient_wa_me_message_general',
            field=models.TextField(default='Bonjour, je vous contacte via MedCare Connect. Je souhaite réserver un rendez-vous pour un examen.', help_text='Bouton principal sur la fiche prestataire. Utilisez {{ org.name }} pour insérer le nom de l’établissement.', verbose_name='Message WhatsApp (contact général)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(help_text='Corps du message — peut contenir des marqueurs du type {{ org.name }}.'),
        ),
    ]
