# Generated by Django 6.0.4 on 2026-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationsettings_patient_wa_me_message_acte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='patient_wa_me_message_devis_formal',
            field=models.TextField(default="Bonjour,\n\nJe vous contacte via MedCare Connect au sujet du devis {{ devis.reference }} — sous-devis {{ devis_part.reference }} — pour {{ org.name }}.\n\nExamens demandés :\n{% for line in lines %}{{ line.line_display }}\n{% endfor %}\nMontant estimé à votre charge : {{ total_display }}.\n\nPouvez-vous confirmer la faisabilité ainsi qu'un créneau disponible ?\n\nMerci.", help_text='Fiche devis → wa.me (un message par structure). Variables Django : devis.reference, devis_part.reference, org.name, total_display ; liste lines avec line_display, acte_name, quantity, subtotal_display (voir encart d’aide sur la page d’édition).', verbose_name='Message WhatsApp (devis formalisé / sous-devis)'),
        ),
    ]
