# Generated by Cursor — templates avis plateforme / structure

from django.db import migrations


POSTED_SUBJ_INAPP = (
    "{% if organisme %}Nouvel avis sur {{ organisme.name }}{% else %}Nouvel avis plateforme MedCare{% endif %}"
)
POSTED_BODY_INAPP = (
    "{{ patient.display_name|default:patient.username }} — note {{ review.rating }}/5. "
    "{% if review.tarifs_delais_comment %}Tarifs & délais : {{ review.tarifs_delais_comment }}"
    "{% elif review.comment %}Commentaire : {{ review.comment }}{% endif %}"
)
POSTED_SUBJ_EMAIL = (
    "[MedCare] {% if organisme %}Nouvel avis — {{ organisme.name }}{% else %}Nouvel avis plateforme MedCare{% endif %}"
)
POSTED_BODY_EMAIL = (
    "Bonjour,\n\nNouvel avis ({{ review.rating }}/5)"
    "{% if organisme %} sur {{ organisme.name }}{% else %} sur la plateforme MedCare{% endif %}.\n"
    "{% if review.tarifs_delais_comment %}Tarifs & délais : {{ review.tarifs_delais_comment }}\n"
    "{% elif review.comment %}Commentaire : {{ review.comment }}\n{% endif %}"
)

APPROVED_SUBJ_INAPP = (
    "{% if organisme %}Avis publié{% else %}Votre avis MedCare est en ligne{% endif %}"
)
APPROVED_BODY_INAPP = (
    "{% if organisme %}Un avis sur {{ organisme.name }} vient d'être validé par la modération."
    "{% else %}Votre avis sur MedCare a été publié après modération. Merci !{% endif %}"
)


def update_review_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    NotificationEvent = apps.get_model("notifications", "NotificationEvent")
    NotificationChannel = apps.get_model("notifications", "NotificationChannel")

    def set_tpl(event_code: str, channel_code: str, subject: str, body: str):
        ev = NotificationEvent.objects.filter(code=event_code).first()
        ch = NotificationChannel.objects.filter(code=channel_code).first()
        if not ev or not ch:
            return
        NotificationTemplate.objects.filter(event=ev, channel=ch).update(
            subject=subject,
            body=body,
        )

    set_tpl("review.posted", "in_app", POSTED_SUBJ_INAPP, POSTED_BODY_INAPP)
    set_tpl("review.posted", "email", POSTED_SUBJ_EMAIL, POSTED_BODY_EMAIL)
    set_tpl("review.approved", "in_app", APPROVED_SUBJ_INAPP, APPROVED_BODY_INAPP)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_patient_wa_me_devis_formal"),
    ]

    operations = [
        migrations.RunPython(update_review_notification_templates, migrations.RunPython.noop),
    ]
