# Generated by Django 6.0.3 on 2026-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_platform_review_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='google_reviews_url',
            field=models.URLField(blank=True, help_text="Lien public vers votre fiche Google (avis). Affiché sur /healthcare/avis/google/. Si ce champ est vide, la variable d'environnement MEDCARE_GOOGLE_REVIEWS_URL est utilisée.", max_length=500, verbose_name='URL « Avis Google » (patients)'),
        ),
    ]
